### ISSUE TITLE
Corpus release plans

### ISSUE THREAD

**Issue by desh2608** [yufan-aslp/AliMeeting#3]
I was wondering if there are any plans to make the data publicly available, now that the challenge is over? I have prepared a [Lhotse](https://github.com/lhotse-speech/lhotse) recipe for the dataset [here](https://github.com/desh2608/lhotse/blob/mini_scale_2022/lhotse/recipes/ali_meeting.py) but I am waiting to push it to master until the corpus is officially available.

**Comment by yufan-aslp** [comment]
AliMeeting corpus is open source. You can download it at the following link:
http://www.openslr.org/119/

**Comment by desh2608** [comment]
Thanks!
