### ISSUE TITLE
Could you please share the room config of 13 recording rooms?

### ISSUE THREAD

**Issue by anogkongda** [yufan-aslp/AliMeeting#5]
Could you please share the room config of 13 rooms mentioned in the challenge description paper?
It is not released on the OpenSLR.
https://www.openslr.org/119

Thank you!

**Comment by anogkongda** [comment]
We would like to reproduce some results in m2met and do some further research for multi-channel multi-party speech recognition, especially for overlapped speech.

**Comment by yufan-aslp** [comment]
You can download room config  of AliMeeting Train set at https://speech-lab-share-data.oss-cn-shanghai.aliyuncs.com/AliMeeting/AliMeeting_Trainset_Room.xlsx

**Comment by anogkongda** [comment]
Thank you so much!
