### ISSUE TITLE
Speaker Diarization Usage

### ISSUE THREAD

**Issue by DTDwind** [yufan-aslp/AliMeeting#6]
Hi~

In your main stage 3 say that Use `scripts/segment_to_lab.sh` to change the file format, but the file is empty......

in your [code](https://github.com/yufan-aslp/AliMeeting/blob/692a034fd510f1720f547c2c91e0fbadc9c24bf2/speaker/run.sh#L77) use `scripts/segment_to_lab.py` directly.

I think this lab format tranform is done, but I still meet some problem.

`run.pl: 4 / 4 failed, log is in ./data/Eval_Ali_far/dia_part/exp/extract_embedding.*.log`

Log in extract_embedding.1.log:
```
INFO:__main__:Start: Processing file R8001_M8004_MS801:

filenames: ['R8001_M8004_MS801' 'R8003_M8001_MS801']
Finished the feature extracting (25181600, 8)
^M  0%|          | 0/251 [00:00<?, ?it/s]^M  0%|          | 0/251 [00:00<?, ?it/s]
INFO:__main__:End:   Processing file R8001_M8004_MS801: Elapsed: 4.490773439407349 seconds
Traceback (most recent call last):
  File "/mnt/HDD/HDD2/DTDwind/vbx_new/AliMeeting/speaker/VBx/predict.py", line 176, in <module>
    fea = features.fbank_htk(seg, window, noverlap, fbank_mx, USEPOWER=True, ZMEANSOURCE=True)
  File "/mnt/HDD/HDD2/DTDwind/vbx_new/AliMeeting/speaker/VBx/features.py", line 101, in fbank_htk
    x *= window
ValueError: operands could not be broadcast together with shapes (322,400,8) (400,) (322,400,8)
# Accounting: time=7 threads=1
# Ended (code 1) at Fri Aug  5 17:28:33 CST 2022, elapsed time 7 seconds
```
Do you know what happen and have any suggest?

Thanks!

**Comment by DTDwind** [comment]
I guess I am missing some pre-processing of the audio files, can you please advise me how to deal with it?
Thank you very much

**Comment by yufan-aslp** [comment]
yes, you may add some pre-processing. You can see "shapes (322,400,8) (400,) (322,400,8)" means our model can only process one-channel audio, but you give a 8-channel audio. So you shou do somre pre-processing to transfer the 8-channel audio to the one-channel audio.

**Comment by DTDwind** [comment]
I hope to reproduce your experiment as much as possible, so I wanna follow you step by step.

May you tell me how your team transfer [AliMeeting](https://www.openslr.org/119) from 8-channel audio to the one-channel audio?

I need the shell to reproduce your work.

Thanks you very much =)

**Comment by yufan-aslp** [comment]
you can use sox.
sox -c 1

**Comment by DTDwind** [comment]
I will try it.
Thanks very very much !
Have a nice day.
